### ISSUE TITLE
FXNumber doesn't seem to work

### ISSUE THREAD

**Issue by georgemoralis** [rrohm/fx-validation#2]
i tried the following

@FXNumber(message="it should be number")
private TextField textNumber;

but validation doesn't seem to work . I looked your test project but i didn't see a sample about it 

Also , it might be usefal in future to provide support for multiple annotations. For example , although not needed probably it might be needed to have the following working

@FXRequired(message="field is required")
@FXNumber(message="it should be number")
private TextField textNumber;

**Comment by rrohm** [comment]
Fix is under development, the example will get updated, too.
Thanks also for the suggestion of having multiple validations on a single control. I add this as a feature request.

**Comment by rrohm** [comment]
The issue should be fixed in the last commit, see also the aeFXValidationTest sample application.
