### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by georgemoralis** [rrohm/fx-validation#4]
It should be nice if we define our custom validation

for example 

@FXCustom(function=customfuction message="...")

boolean customfuction()
{
   if(validation is ok)
     return true;
  else 
    return false;
}

**Comment by rrohm** [comment]
You are right. For the sake of type safety, I think it should look somehow like: 
@FXCustomValidation(validation=<? extends FXAbstractValidator>,  message="...")

Actually, the currently available standard annotations allow overriding the default validation class. This is (at present) neither documented nor tested, but should make it easy. Nevertheless, I better will provide an annotation for this purpose.

**Comment by rrohm** [comment]
I pushed a new version that supports custom validators, also updated docs and a wiki page. 
I'm looking forward to comments - if the solution fits, I will close the issue.

**Comment by georgemoralis** [comment]
getting the following error when trying to run the test

Caused by: javafx.fxml.LoadException: Resource "text.title.customvalidation" not found.
...../aeFXValidationTest/dist/run1172421619/aeFXValidationTest.jar!/com/aeonium/aefxvalidationtest/FXMLDocument.fxml:235

**Comment by rrohm** [comment]
How did you try to start the application?
The exception suggests that there is an older version of the resource bundle. If I do a full clone from fx-actions and fx-validation, the aeFXValidationTest app compiles, and runs without the exception, so the code in the repository should be OK. Is it possible that the working copy of  fx-validation is not fuly up-to-date?

**Comment by georgemoralis** [comment]
figured out. You are missing  

text.title.customvalidation=....

in text.properties

**Comment by rrohm** [comment]
Ah, I saw it :-( 
Sorry, I missed that – the JVM is running on another locale.
Thank you!

**Comment by rrohm** [comment]
It's time to think about JavaFX UI testing with localizations ...

**Comment by georgemoralis** [comment]
yah no bad idea.

another case i can think of is disable validation in request.

For example i have a case of checking if a number in textfield is a valid VAT number with custom validation. I have a checkbox that i would like to bind with textfield to disable this validation rule.

**Comment by rrohm** [comment]
It's on board, now: 
 @FXML
 @FXValidation(validation = CustomValidator.class)
 private TextField tfCustom;

I'm closing this issue and look forward to feedback.
